FROM node:23-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm install

FROM base AS builder

COPY . .

RUN npm run build

FROM nginx:alpine AS runner

COPY --from=builder /app/next.config.js /app/public ./

COPY --from=builder /app/.next/standalone ./

COPY --from=builder /app/.next/static ./app/.next/static

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
